apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: user-service
  title: User Management Service
  description: User profiles, preferences, and management service for Conga Platform
  annotations:
    github.com/project-slug: testorg08/user-service
    argocd/app-name: user-service-dev
    backstage.io/techdocs-ref: dir:.
    conga.io/site-group: CSG1
    conga.io/sync-wave: "2"
    conga.io/database-dependencies: user_database
    conga.io/infrastructure-requirements: postgresql,redis,s3
    # CI/CD Integration
    github.com/workflows: ci-cd.yaml
    backstage.io/kubernetes-id: user-service
    backstage.io/kubernetes-namespace: csg1-dev,csg1-staging
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/name=user-service'
  tags:
    - users
    - profiles
    - management
    - platform
    - csg1
  links:
    - url: https://users-dev.conga.com
      title: Development Environment
      icon: web
    - url: https://users-staging.conga.com
      title: Staging Environment
      icon: web
    - url: https://users.conga.com
      title: Production Environment
      icon: web
    - url: https://github.com/testorg08/user-service/actions
      title: GitHub Actions
      icon: github
    - url: https://localhost:8080/applications/user-service-dev
      title: ArgoCD Dev
      icon: dashboard
    - url: https://localhost:8080/applications/user-service-staging
      title: ArgoCD Staging
      icon: dashboard
spec:
  type: service
  lifecycle: production
  owner: platform-team
  system: conga-platform-core
  providesApis:
    - user-api
  dependsOn:
    - component:auth-service
    - component:config-service